### ISSUE TITLE
Inconsistent docs for slurm integration

### ISSUE THREAD

**Issue by sjpb** [waldur/waldur-site-agent#1]
Hi, we're trying to trial integrating Waldur + Keycloak with an existing Slurm cluster which uses FreeIPA.

There are two pages which reference this repo:
1. https://docs.waldur.com/admin-guide/providers/remote-slurm/: This talks about deploying 3x instances of the agent. The linked env files have `WALDUR_SYNC_DIRECTION` values of `membership_sync`, `report` and `order_process`. These don't appear to match the [current code](https://github.com/waldur/waldur-site-agent/blob/0.2.4/waldur_site_agent/__init__.py#L13).
2. https://docs.waldur.com/integrations/waldur-slurm-service/: This has `WALDUR_SYNC_DIRECTION` which uses `push` and `pull` values which do match the current code.

There's also a 3rd page https://docs.waldur.com/admin-guide/providers/slurm/ - which is not clear on what the difference is from the `providers/remote-slurm` URL, although it looks like maybe this is actually a wider view of configuration related to #2 above.

Any advice on which docs to follow, and which are maybe outdated, would be appreciated!

**Comment by sjpb** [comment]
Ok thank you, I appreciate the fast response.

**Comment by livenson** [comment]
Ok, new site agent has been released (0.3.0 version) and docs have been updated a bit. Works in development, would you care to validate too, @sjpb ?

Documentation link is here: https://docs.waldur.com/admin-guide/providers/remote-slurm/#integration-with-the-site
